# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=b'images/photo/'),
        ),
    ]
