# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160419_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
