# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160428_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date_started',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
