# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20160526_1215'),
        ('projects', '0004_auto_20160428_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_image', to='images.Image'),
        ),
    ]
