# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0007_auto_20160526_1215'),
        ('video', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('title_image', models.ImageField(blank=True, upload_to=b'images/news/')),
                ('images', models.ManyToManyField(blank=True, to='images.Image')),
                ('video', models.ManyToManyField(blank=True, to='video.Video')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
