# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
