# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('strategy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
            options={
                'verbose_name_plural': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Strategy',
            },
            bases=('strategy.paragraph',),
        ),
    ]
