# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='person',
            new_name='related_person',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='person',
            new_name='related_person',
        ),
    ]
