# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160419_1623'),
        ('about', '0002_auto_20160419_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='related_person',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='related_person',
        ),
        migrations.AddField(
            model_name='advisor',
            name='relatedperson_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.RelatedPerson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='relatedperson_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.RelatedPerson'),
            preserve_default=False,
        ),
    ]
